"""
Localization module for LLMChan.

https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers
https://partner.steamgames.com/doc/store/localization/languages
"""

from typing import Literal

Language = Literal[
    "arabic",
    "bulgarian",
    "chinese-cn",
    "chinese-sg",
    "chinese-tw",
    "czech",
    "danish",
    "dutch",
    "english",
    "finnish",
    "french",
    "german",
    "greek",
    "hungarian",
    "indonesian",
    "italian",
    "japanese",
    "korean",
    "norwegian",
    "polish",
    "portuguese",
    "brazilian",
    "romanian",
    "russian",
    "spanish",
    "latam",
    "swedish",
    "thai",
    "turkish",
    "ukrainian",
    "vietnamese",
    # Additional languages
    "afrikaans",
    "albanian",
    "amharic",
    "armenian",
    "assamese",
    "azerbaijani",
    "basque",
    "bengali",  # = "bangla"
    "belarusian",
    "bosnian",
    "catalan",
    "cherokee",
    "croatian",
    "dari",
    "estonian",
    "filipino",  # = "tagalog"
    "galician",
    "georgian",
    "gujarati",
    "gurmukhi",  # punjabi (gurmukhi)
    "hausa",
    "hebrew",
    "hindi",
    "icelandic",
    "igbo",
    "irish",
    "kannada",
    "kazakh",
    "khmer",
    "k'iche",
    "kinyarwanda",
    "konkani",
    "kyrgyz",
    "latvian",
    "lithuanian",
    "luxembourgish",
    "macedonian",
    "malay",
    "malayalam",
    "maltese",
    "maori",
    "marathi",
    "mongolian",
    "nepali",
    "odia",
    "persian",  # = "farsi"
    "quechua",
    "scots",  # = "scottish gaelic"
    "serbian",
    "shahmukhi",  # punjabi (shahmukhi)
    "sindhi",
    "sinhala",
    "slovak",
    "slovenian",
    "sorani",  # = "kurdish (sorani)"
    "sotho",
    "swahili",
    "tajik",
    "tamil",
    "tatar",
    "telugu",
    "tigrinya",
    "tswana",
    "turkmen",
    "urdu",
    "uyghur",
    "uzbek",
    "valencian",
    "welsh",
    "wolof",
    "xhosa",
    "yoruba",
    "zulu",
    # Extra languages
    "egyptian",  # egyptian arabic
    "javanese",
    "nigerian",  # nigeria pidgin
    "wu",  # chinese (wu)
    "yue",  # chinese (yue) = cantonese
]


LangPromptDict: dict[Language, str] = {
    "english": "",
    "arabic": "Use Arabic language only; أجب باللغة العربية من فضلك.",
    "bulgarian": "Use Bulgarian language only; Отговорете на български, моля.",
    "chinese-cn": "Use Chinese language only; 请用中文回答。",
    "chinese-sg": "Use Singaporean Mandarin language only; 请用新加坡华语回答。",
    "chinese-tw": "Use Taiwnese Mandarin language only; 請用國語回答。",
    "czech": "Use Czech language only; Odpovězte, prosím, česky.",
    "danish": "Use Danish language only; Besvar venligst på dansk.",
    "dutch": "Use Dutch language only; Antwoord alstublieft in het Nederlands.",
    "finnish": "Use Finnish language only; Vastaa suomeksi, kiitos.",
    "greek": "Use Greek language only; Απαντήστε στα ελληνικά, παρακαλώ.",
    "hungarian": "Use Hungarian language only; Kérem, válaszoljon magyarul.",
    "french": "Use French language only; Répondez en français, s'il vous plaît.",
    "german": "Use German language only; Bitte antworten Sie auf Deutsch.",
    "indonesian": "Use Indonesian language only; Tolong jawab dalam bahasa Indonesia.",
    "italian": "Use Italian language only; Rispondi in italiano, per favore.",
    "japanese": "Use Japanese language only; 日本語で答えてください。",
    "korean": "Use Korean language only; 한국어로 답변해주세요.",
    "norwegian": "Use Norwegian language only; Vennligst svar på norsk.",
    "polish": "Use Polish language only; Odpowiedz po polsku, proszę.",
    "romanian": "Use Romanian language only; Răspundeți în limba română, vă rog.",
    "portuguese": "Use Portuguese language only; Responda em português, por favor.",
    "brazilian": "Use Brazilian Portuguese language only; Responda em português do Brasil, por favor.",
    "russian": "Use Russian language only; Ответьте на русском языке, пожалуйста.",
    "spanish": "Use Spanish language only; Responde en español, por favor.",
    "latam": "Use Latin American Spanish language only; Responde en español latinoamericano, por favor.",
    "swedish": "Use Swedish language only; Vänligen svara på svenska.",
    "thai": "Use Thai language only; โปรดตอบด้วยภาษาไทย",
    "turkish": "Use Turkish language only; Lütfen Türkçe cevap verin.",
    "vietnamese": "Use Vietnamese language only; Trả lời bằng tiếng Việt, xin cảm ơn.",
    "ukrainian": "Use Ukrainian language only; Будь ласка, відповідайте українською.",
    # Additional languages
    "afrikaans": "Use Afrikaans language only; Antwoord asseblief in Afrikaans.",
    "albanian": "Use Albanian language only; Përgjigju në gjuhën shqipe, ju lutem.",
    "amharic": "Use Amharic language only; እባክዎ በአማርኛ እባክዎ አስተያየት አስፈላጊውን እባክዎ።",
    "armenian": "Use Armenian language only; Խնդրում եմ պատասխանել հայերեն։",
    "assamese": "Use Assamese language only; অনুগ্ৰহ কৰি অসমীয়া ভাষাত উত্তৰ দিবলৈ প্ৰয়াস কৰক।",
    "azerbaijani": "Use Azerbaijani language only; Zəhmət olmasa, cavabı azərbaycan dilində verin.",
    "basque": "Use Basque language only; Erantzun euskaraz, mesedez.",
    "bengali": "Use Bengali language only; দয়া করে বাংলা ভাষায় উত্তর দিন।",
    "belarusian": "Use Belarusian language only; Калі ласка, адказвайце на беларускай мове.",
    "bosnian": "Use Bosnian language only; Odgovorite na bosanskom jeziku, molim vas.",
    "catalan": "Use Catalan language only; Respon en català, si us plau.",
    "cherokee": "Use Cherokee language only; ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ ᎦᏬᏂᎯᏍᏗᏍᎩ ᎦᏬᏂᎯᏍᏗᏍᎩᏂ.",
    "croatian": "Use Croatian language only; Odgovorite na hrvatskom jeziku, molim vas.",
    "dari": "Use Dari language only; لطفاً به زبان دری پاسخ دهید.",
    "estonian": "Use Estonian language only; Palun vastake eesti keeles.",
    "filipino": "Use Filipino language only; Sumagot sa Filipino, salamat.",
    "galician": "Use Galician language only; Responda en galego, por favor.",
    "georgian": "Use Georgian language only; გთხოვთ, უპასუხოთ ქართულად.",
    "gujarati": "Use Gujarati language only; કૃપા કરીને ગુજરાતી ભાષામાં જવાબ આપો.",
    "gurmukhi": "Use Punjabi (Gurmukhi) language only; ਕਿਰਪਾ ਕਰਕੇ ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ) ਭਾਸ਼ਾ ਵਿੱਚ ਜਵਾਬ ਦਿਓ।",
    "hausa": "Use Hausa language only; Don Allah amsa da harshe.",
    "hebrew": "Use Hebrew language only; ענה בעברית בבקשה.",
    "hindi": "Use Hindi language only; कृपया हिंदी में जवाब दें।",
    "icelandic": "Use Icelandic language only; Vinsamlegast svaraðu á íslensku.",
    "igbo": "Use Igbo language only; Biko jiri Igbo.",
    "irish": "Use Irish language only; Freagair as Gaeilge, le do thoil.",
    "kannada": "Use Kannada language only; ದಯವಿಟ್ಟು ಕನ್ನಡದಲ್ಲಿ ಉತ್ತರಿಸಿ.",
    "kazakh": "Use Kazakh language only; Қазақ тілінде жауап беріңіз.",
    "khmer": "Use Khmer language only; សូមឆ្លើយជាភាសាខ្មែរ។",
    "k'iche": "Use K'iche' language only; Xuk'ulem ri K'iche', xin k'utb'anoj.",
    "kinyarwanda": "Use Kinyarwanda language only; Komeza ukomeze mu Kinyarwanda.",
    "konkani": "Use Konkani language only; कृपया कोंकणी भाषेत उत्तर द्या.",
    "kyrgyz": "Use Kyrgyz language only; Кыргыз тилинде жооп бериңиз.",
    "latvian": "Use Latvian language only; Lūdzu, atbildiet latviski.",
    "lithuanian": "Use Lithuanian language only; Atsakykite lietuviškai, prašome.",
    "luxembourgish": "Use Luxembourgish language only; Äntwert op Lëtzebuergesch, w.e.g.",
    "macedonian": "Use Macedonian language only; Ве молам одговорете на македонски.",
    "malay": "Use Malay language only; Sila jawab dalam bahasa Melayu.",
    "malayalam": "Use Malayalam language only; മലയാളത്തില്‍ ഉത്തരം നല്‍കുക.",
    "maltese": "Use Maltese language only; Jekk jogħġbok, ibgħat risposta bil-Malti.",
    "maori": "Use Maori language only; Whakautu i roto i te reo Māori, tēnā.",
    "marathi": "Use Marathi language only; कृपया मराठी भाषेत उत्तर द्या.",
    "mongolian": "Use Mongolian language only; Монгол хэлээр хариулна уу.",
    "nepali": "Use Nepali language only; कृपया नेपालीमा उत्तर दिनुहोस्।",
    "odia": "Use Odia language only; ଓଡ଼ିଆରେ ଉତ୍ତର ଦିଅନ୍ତୁ।",
    "persian": "Use Persian language only; لطفاً به فارسی پاسخ دهید.",
    "quechua": "Use Quechua language only; Atin rimanakuy kichwapi.",
    "scots": "Use Scottish Gaelic language only; Freagair sa Ghàidhlig, mas e do thoil e.",
    "serbian": "Use Serbian language only; Одговорите на српском језику, молим вас.",
    "shahmukhi": "Use Punjabi (Shahmukhi) language only; کرپا کرکے پنجابی (شاہ مکھی) زبان میں جواب دیں۔",
    "sindhi": "Use Sindhi language only; ڪريپيا سنڌي ٻولي ۾ جواب ڏيو.",
    "sinhala": "Use Sinhala language only; සිංහලේ භාවිතා කරන්න.",
    "slovak": "Use Slovak language only; Odpovedajte, prosím, po slovensky.",
    "slovenian": "Use Slovenian language only; Odgovorite v slovenščini, prosim.",
    "sorani": "Use Kurdish (Sorani) language only; تکایە بە سۆرانی جواب بدە.",
    "sotho": "Use Sotho language only; Ka kopo bapalla ka Sesotho.",
    "swahili": "Use Swahili language only; Tafadhali jibu kwa Kiswahili.",
    "tajik": "Use Tajik language only; Лутфан, ба забони тоҷикӣ ҷавоб диҳед.",
    "tamil": "Use Tamil language only; தயவுசெய்து தமிழ் மொழியில் பதில் சொல்லவும்.",
    "tatar": "Use Tatar language only; Татар телеүе җавап бирегез.",
    "telugu": "Use Telugu language only; దయచేసి తెలుగు భాషలో జవాబు ఇవ్వండి.",
    "tigrinya": "Use Tigrinya language only; እቲ ትግርኛ ቋንቋ እዚ ጸሓፍ ክርእየኩም።",
    "tswana": "Use Tswana language only; Ka kopo bontsha ka Setswana.",
    "turkmen": "Use Turkmen language only; Türkmen dilinde jogap bermäge rica edýäris.",
    "urdu": "Use Urdu language only; براہ کرم اردو زبان میں جواب دیں۔",
    "uyghur": "Use Uyghur language only; ئۇيغۇر تىلىدا جاۋاب بېرىڭ.",
    "uzbek": "Use Uzbek language only; Iltimos, o'zbek tilida javob bering.",
    "valencian": "Use Valencian language only; Respon en valencià, si us plau.",
    "welsh": "Use Welsh language only; Atebwch yn Gymraeg, os gwelwch yn dda.",
    "wolof": "Use Wolof language only; Noppal sa Wolof, jërejëf.",
    "xhosa": "Use Xhosa language only; Nceda ulondoloze nge-Xhosa.",
    "yoruba": "Use Yoruba language only; Jọwọ jẹ irọ Yorùbá.",
    "zulu": "Use Zulu language only; Khumbula ukuthi uzibuze ngesiZulu.",
    ## Extra languages
    "egyptian": "Use Egyptian Arabic language only; ارد عربي بس.",
    "javanese": "Use Javanese language only; Mugi samubarang nganggo basa Jawa.",
    "nigerian": "Use Nigerian Pidgin language only; Abeg ansa for Nigerian Pidgin.",
    "wu": "Use Wu Chinese language only; 请用吴语回答。",
    "yue": "Use Cantonese language only; 請用粵語回答。",
}


LangList: list[Language] = sorted(
    [
        "arabic",
        "bulgarian",
        "chinese-cn",
        "chinese-sg",
        "chinese-tw",
        "czech",
        "danish",
        "dutch",
        "english",
        "finnish",
        "french",
        "german",
        "greek",
        "hungarian",
        "indonesian",
        "italian",
        "japanese",
        "korean",
        "norwegian",
        "polish",
        "portuguese",
        "brazilian",
        "romanian",
        "russian",
        "spanish",
        "latam",
        "swedish",
        "thai",
        "turkish",
        "ukrainian",
        "vietnamese",
        # Additional languages
        "afrikaans",
        "albanian",
        "amharic",
        "armenian",
        "assamese",
        "azerbaijani",
        "basque",
        "bengali",  # = "bangla"
        "belarusian",
        "bosnian",
        "catalan",
        "cherokee",
        "croatian",
        "dari",
        "estonian",
        "filipino",  # = "tagalog"
        "galician",
        "georgian",
        "gujarati",
        "gurmukhi",  # punjabi (gurmukhi)
        "hausa",
        "hebrew",
        "hindi",
        "icelandic",
        "igbo",
        "irish",
        "kannada",
        "kazakh",
        "khmer",
        "k'iche",
        "kinyarwanda",
        "konkani",
        "kyrgyz",
        "latvian",
        "lithuanian",
        "luxembourgish",
        "macedonian",
        "malay",
        "malayalam",
        "maltese",
        "maori",
        "marathi",
        "mongolian",
        "nepali",
        "odia",
        "persian",  # = "farsi"
        "quechua",
        "scots",  # = "scottish gaelic"
        "serbian",
        "shahmukhi",  # punjabi (shahmukhi)
        "sindhi",
        "sinhala",
        "slovak",
        "slovenian",
        "sorani",  # = "kurdish (sorani)"
        "sotho",
        "swahili",
        "tajik",
        "tamil",
        "tatar",
        "telugu",
        "tigrinya",
        "tswana",
        "turkmen",
        "urdu",
        "uyghur",
        "uzbek",
        "valencian",
        "welsh",
        "wolof",
        "xhosa",
        "yoruba",
        "zulu",
        # Extra languages
        "egyptian",  # egyptian arabic
        "javanese",
        "nigerian",  # nigeria pidgin
        "wu",  # chinese (wu)
        "yue",  # chinese (yue) = cantonese
    ]
)
